### ISSUE TITLE
Update recommended gas price strategy

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/merkle-funder#57]
Airnode v0.12 will introduce a new gas price strategy. Similar to https://github.com/api3dao/airseeker/issues/426 we should bump the dependency and recommend that to be used over provider-recommended.

**Comment by metobom** [comment]
[Airnode v0.12](https://github.com/api3dao/airnode/releases/tag/v0.12.0) is released so this is not blocked anymore.
